Added instructions on installing psycopg2 using psycopg2-binary
hotosm/raw-data-api pull request #239
Opened 2024-03-23 12:39 UTC by robel16

## What type of PR is this? 
>Check all applicable

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue :

- Resolve #123example

## What does this PR do ?

A brief description of how this solves the issue.

## Consideration : 

Are there any alternatives considered / tried out during development for solution ? Any specific decision made ? if Yes , explain 

## How to test ? 

Notes for the reviewer. How to test this change?

## Screenshots :

Please provide screenshots of the change.

## Checklists:

Checklist before requesting review : 

- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-27 12:57 UTC, kshitijrajsharma commented
psycopg2-binary is recommended only for development and not for production , Lets mention that too

2024-03-27 13:01 UTC, kshitijrajsharma requested changes

2024-03-27 13:01 UTC, kshitijrajsharma commented on backend/Readme.md
> +  Example of geojson :
From here on All the installation instructions are moved to code block . Do verify that and make sure it is readable. You can preview your file and you will notice something like this 
<img width="1206" alt="image" src="https://github.com/hotosm/raw-data-api/assets/36752999/891f2f91-10e2-4974-a128-d48a314936ce">

2024-03-27 19:20 UTC, robel16 commented
@kshitijrajsharma  I have updated it as you requested can you please review?

2024-03-30 15:18 UTC, robel16 commented
Hello @kshitijrajsharma  can you please review the PR I have edited the Readme as you requested

2025-08-19 14:44 UTC, closed without merging